#!/usr/bin/env bash
# NEUTRON EVO OS — Compact Wrapper
# Wraps /compact to auto-checkpoint before and after compaction.
# Usage: Call this INSTEAD of /compact in Claude Code sessions.
#   /compact_wrapper Continue the task...
#
# How it works:
#   1. Writes a checkpoint BEFORE compaction (state preservation)
#   2. Instructs Claude to /compact with focus preservation
#   3. Saves handoff note for post-compaction recovery

set -euo pipefail

# Detect NEUTRON_ROOT: use env var, or resolve from this script's location.
# portable across: local dev, ~/.neutron-evo-os, /opt/neutron-evo-os, etc.
if [ -z "${NEUTRON_ROOT:-}" ]; then
    # Resolve this script's real path (follows symlinks)
    _REAL_PATH="$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}" 2>/dev/null || echo "${BASH_SOURCE[0]}")")" && pwd)"
    NEUTRON_ROOT="$(cd "$_REAL_PATH/.." && pwd)"
fi
MEMORY_DIR="$NEUTRON_ROOT/memory"
CHECKPOINT_CLI="$NEUTRON_ROOT/engine/checkpoint_cli.py"

# Get today's date for checkpoint naming
TODAY=$(date +%Y-%m-%d)
TIMESTAMP=$(date +%Y-%m-%d_%H:%M:%S)

# Focus arguments passed to the wrapper
FOCUS="${1:-session recovery}"

echo "[NEUTRON] Compact Wrapper — checkpointing before /compact"

# Step 1: Auto-detect modified files from git (safe on non-git repos)
MODIFIED=""
if [ -d "$NEUTRON_ROOT/.git" ]; then
    MODIFIED=$(git -C "$NEUTRON_ROOT" diff --name-only 2>/dev/null | tr '\n' ',' || echo "")
fi
if [ -z "${MODIFIED}" ] || [ "$MODIFIED" = "," ]; then
    MODIFIED=""
fi

# Step 2: Verify checkpoint CLI exists
if [ ! -f "$CHECKPOINT_CLI" ]; then
    echo "ERROR: checkpoint_cli.py not found at $CHECKPOINT_CLI"
    exit 1
fi

# Step 3: Write pre-compact checkpoint
# Pass each modified file as a separate --modified argument
echo "[NEUTRON] Writing pre-compact checkpoint..."
if [ -n "$MODIFIED" ] && [ "$MODIFIED" != "," ]; then
    # Parse comma-separated into individual --modified args
    python3 "$CHECKPOINT_CLI" \
        --task "Pre-compact checkpoint" \
        --focus "$FOCUS" \
        --status "paused" \
        --notes "Checkpoint written by compact_wrapper.sh before /compact at $TIMESTAMP. Modified files: $MODIFIED" \
        --confidence "high" \
        $(echo "$MODIFIED" | tr ',' '\n' | while read -r f; do
            [ -n "$f" ] && echo "--modified" "$f"
        done) \
        > /dev/null 2>&1 || true
else
    python3 "$CHECKPOINT_CLI" \
        --task "Pre-compact checkpoint" \
        --focus "$FOCUS" \
        --status "paused" \
        --notes "Checkpoint written by compact_wrapper.sh before /compact at $TIMESTAMP" \
        --confidence "high" \
        > /dev/null 2>&1 || true
fi

# Step 4: Create handoff note for post-compact recovery
HANDOFF_FILE="$MEMORY_DIR/handoff_$TODAY.md"
cat > "$HANDOFF_FILE" << EOF
# Handoff Note — $TIMESTAMP

> Auto-generated by compact_wrapper.sh
> NEUTRON EVO OS v4.3.2

## Pre-Compact State
- **Timestamp**: $TIMESTAMP
- **Focus**: $FOCUS
- **Modified files**: ${MODIFIED:-none}
- **Checkpoint**: memory/$TODAY.md

## Recovery Instructions
After /compact completes, read memory/$TODAY.md to restore context.

## Resume Command
\`\`\`
python3 $CHECKPOINT_CLI --read
\`\`\`

## Post-Compact Checklist
- [ ] Read checkpoint from memory/$TODAY.md
- [ ] Confirm current task matches checkpoint
- [ ] Verify modified files still present
- [ ] Resume with: "$FOCUS"
EOF

echo "[NEUTRON] Checkpoint saved to memory/$TODAY.md"
echo "[NEUTRON] Handoff note: $HANDOFF_FILE"
echo ""
echo "Now execute: /compact $FOCUS"
echo "After compact, Claude will re-read CLAUDE.md + checkpoint automatically."
